// Flattens src/*.js into one file you can paste into the Cloudflare dashboard,
// so setting the bot up needs no Node, no wrangler and no terminal.
//
// This is not a general bundler and does not try to be. It works because the
// modules here import in one direction only and nothing is imported twice under
// two names:
//
//   batch.js, telegram.js   import nothing
//   bot.js                  imports both
//   index.js                imports all three
//
// So: concatenate in that order, drop the import lines, drop the `export`
// keywords, and rebuild the two namespace objects the code reads through.
//
// Run: node worker/build.mjs
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const SRC = join(HERE, 'src');
const OUT = join(HERE, 'dist', 'worker.js');

// In dependency order. `ns` is the name the other modules read it through.
const MODULES = [
  { file: 'batch.js', ns: 'batch' },
  { file: 'telegram.js', ns: 'tg' },
  { file: 'caption.js', ns: null },
  { file: 'bot.js', ns: null },
  { file: 'index.js', ns: null },
];

/** Every name a module exports, so the namespace object can be rebuilt. */
function exportedNames(source) {
  const names = new Set();
  const patterns = [
    /^export\s+(?:async\s+)?function\s+([A-Za-z_$][\w$]*)/gm,
    /^export\s+(?:const|let|var)\s+([A-Za-z_$][\w$]*)/gm,
  ];
  for (const re of patterns) {
    for (const m of source.matchAll(re)) names.add(m[1]);
  }
  return [...names];
}

function strip(source) {
  return source
    // Import lines, single or multi-line.
    .replace(/^import\s+[\s\S]*?from\s+'[^']+';\s*$/gm, '')
    // `export default {` must survive — it is the Worker's entry point.
    .replace(/^export\s+(?!default)/gm, '')
    .trim();
}

// The caption library comes from the app's own source, so the bot hints the
// model with exactly the wording the report prints and there is no second copy
// to drift. The office can still push its own edits over the top at runtime.
const { DEFAULT_CAPTIONS } = await import('../js/captions.js');

const parts = [
  '// Insta Report intake bot — built file, do not edit.',
  '// Generated by worker/build.mjs from worker/src/. Paste this whole file into',
  '// the Cloudflare Worker editor; see worker/SETUP.md.',
  '',
  '/* ---------- caption library, from js/captions.js ---------- */',
  '',
  `const DEFAULT_LIBRARY = ${JSON.stringify(DEFAULT_CAPTIONS)};`,
  '',
];

for (const mod of MODULES) {
  const source = await readFile(join(SRC, mod.file), 'utf8');
  parts.push(`/* ---------- ${mod.file} ---------- */`, '', strip(source), '');
  if (mod.ns) {
    const names = exportedNames(source);
    if (!names.length) throw new Error(`${mod.file} exports nothing to namespace`);
    parts.push(`const ${mod.ns} = { ${names.join(', ')} };`, '');
  }
}

const bundle = `${parts.join('\n')}\n`;

// A flattened file has one failure mode worth guarding: two modules declaring
// the same top-level name, which would silently shadow rather than error.
const declared = [...bundle.matchAll(/^(?:async\s+)?function\s+([A-Za-z_$][\w$]*)|^(?:const|let|var)\s+([A-Za-z_$][\w$]*)/gm)]
  .map((m) => m[1] || m[2]);
const clashes = declared.filter((n, i) => declared.indexOf(n) !== i);
if (clashes.length) {
  throw new Error(`name clash after flattening: ${[...new Set(clashes)].join(', ')}`
    + '\nRename one of them in src/ — the bundle would shadow it silently.');
}

await mkdir(dirname(OUT), { recursive: true });
await writeFile(OUT, bundle);
console.log(`built worker/dist/worker.js — ${(bundle.length / 1024).toFixed(1)}KB, `
  + `${bundle.split('\n').length} lines`);
