// Flattens src/*.js into one file you can paste into the Cloudflare dashboard,
// so setting the bot up needs no Node, no wrangler and no terminal.
//
// This is not a general bundler and does not try to be. It works because the
// modules here import in one direction only and nothing is imported twice under
// two names:
//
//   batch.js, telegram.js   import nothing
//   bot.js                  imports both
//   index.js                imports all three
//
// So: concatenate in that order, drop the import lines, drop the `export`
// keywords, and rebuild the two namespace objects the code reads through.
//
// Run: node worker/build.mjs
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const SRC = join(HERE, 'src');
const OUT = join(HERE, 'dist', 'worker.js');

// In dependency order. `ns` is the name the other modules read it through.
const MODULES = [
  { file: 'batch.js', ns: 'batch' },
  { file: 'telegram.js', ns: 'tg' },
  { file: 'bot.js', ns: null },
  { file: 'index.js', ns: null },
];

/** Every name a module exports, so the namespace object can be rebuilt. */
function exportedNames(source) {
  const names = new Set();
  const patterns = [
    /^export\s+(?:async\s+)?function\s+([A-Za-z_$][\w$]*)/gm,
    /^export\s+(?:const|let|var)\s+([A-Za-z_$][\w$]*)/gm,
  ];
  for (const re of patterns) {
    for (const m of source.matchAll(re)) names.add(m[1]);
  }
  return [...names];
}

function strip(source) {
  return source
    // Import lines, single or multi-line.
    .replace(/^import\s+[\s\S]*?from\s+'[^']+';\s*$/gm, '')
    // `export default {` must survive — it is the Worker's entry point.
    .replace(/^export\s+(?!default)/gm, '')
    .trim();
}

const parts = [
  '// Insta Report intake bot — built file, do not edit.',
  '// Generated by worker/build.mjs from worker/src/. Paste this whole file into',
  '// the Cloudflare Worker editor; see worker/SETUP.md.',
  '',
  '// Which build this is. /health reports it back, so "is my paste live?" is',
  '// one look rather than an afternoon.',
  "const BUILD_STAMP = '@@STAMP@@';",
  '',
];

for (const mod of MODULES) {
  const source = await readFile(join(SRC, mod.file), 'utf8');
  parts.push(`/* ---------- ${mod.file} ---------- */`, '', strip(source), '');
  if (mod.ns) {
    const names = exportedNames(source);
    if (!names.length) throw new Error(`${mod.file} exports nothing to namespace`);
    parts.push(`const ${mod.ns} = { ${names.join(', ')} };`, '');
  }
}

// A fingerprint of this exact file, which /health reports back. Pasting into a
// dashboard is a step with no receipt: an out-of-date paste looks identical to
// a current one, and twice now an hour has gone into a bug that was really an
// old file still running. Content-hashed rather than versioned, so it cannot
// drift from what is in the file. The placeholder is hashed in its own place so
// the stamp is stable — hashing the finished text would include the stamp.
const MARK = '@@STAMP@@';
const body = `${parts.join('\n')}\n`;
const stamp = createHash('sha256').update(body).digest('hex').slice(0, 8);
const bundle = body.replace(MARK, stamp);
if (!body.includes(MARK)) throw new Error('the build stamp placeholder went missing');

// A flattened file has one failure mode worth guarding: two modules declaring
// the same top-level name, which would silently shadow rather than error.
const declared = [...bundle.matchAll(/^(?:async\s+)?function\s+([A-Za-z_$][\w$]*)|^(?:const|let|var)\s+([A-Za-z_$][\w$]*)/gm)]
  .map((m) => m[1] || m[2]);
const clashes = declared.filter((n, i) => declared.indexOf(n) !== i);
if (clashes.length) {
  throw new Error(`name clash after flattening: ${[...new Set(clashes)].join(', ')}`
    + '\nRename one of them in src/ — the bundle would shadow it silently.');
}

await mkdir(dirname(OUT), { recursive: true });
await writeFile(OUT, bundle);
console.log(`built worker/dist/worker.js — ${(bundle.length / 1024).toFixed(1)}KB, `
  + `${bundle.split('\n').length} lines, build ${stamp}`);
console.log(`   /health on the deployed Worker must report build ${stamp}`);
