// Produces both apps from this one source tree into dist/:
//
//   dist/index.html   a chooser, so one link covers both
//   dist/admin/       full app  — AI assistant, report, full backup
//   dist/site/        capture   — no assistant, no key, smaller photos
//
// Run: node tools/build.mjs
import { cp, mkdir, rm, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const DIST = join(ROOT, 'dist');

const SOURCE = ['index.html', 'manifest.webmanifest', 'sw.js', 'css', 'js', 'icons'];

const VARIANTS = [
  {
    dir: 'admin',
    build: {
      id: 'admin',
      name: 'Insta Report',
      shortName: 'Insta Report',
      dbName: 'instareport',
      ai: true,
      fullBackup: true,
      defaultImageMaxPx: 1600,
    },
    // Files the capture build has no use for.
    drop: [],
  },
  {
    dir: 'site',
    build: {
      id: 'site',
      name: 'Insta Report Site',
      shortName: 'IR Site',
      dbName: 'instareport-site',
      ai: false,
      fullBackup: false,
      defaultImageMaxPx: 1200,
    },
    drop: ['js/ai.js', 'js/screens/assistant.js'],
  },
];

const buildModule = (b) => `// Generated by tools/build.mjs — do not edit in dist/.
export const BUILD = ${JSON.stringify(b, null, 2)};
`;

async function edit(path, fn) {
  await writeFile(path, fn(await readFile(path, 'utf8')));
}

async function variant(v) {
  const out = join(DIST, v.dir);
  await mkdir(out, { recursive: true });
  for (const item of SOURCE) {
    await cp(join(ROOT, item), join(out, item), { recursive: true });
  }
  for (const dead of v.drop) await rm(join(out, dead), { force: true });

  await writeFile(join(out, 'js/build.js'), buildModule(v.build));

  await edit(join(out, 'index.html'), (s) => s
    .replace(/<title>[^<]*<\/title>/, `<title>${v.build.name}</title>`)
    .replace(/(name="apple-mobile-web-app-title" content=")[^"]*/, `$1${v.build.shortName}`));

  await edit(join(out, 'manifest.webmanifest'), (s) => {
    const m = JSON.parse(s);
    m.name = `${v.build.name} — Inspection Reports`;
    m.short_name = v.build.shortName;
    // Two installable apps on one origin need distinct identities, or the
    // browser treats the second install as the first app.
    m.id = `./${v.dir}/`;
    m.description = v.build.ai
      ? 'Offline-first building inspection reports with AI-assisted captions.'
      : 'Offline-first defect capture for site teams. Photos, captions and one file for the office.';
    return JSON.stringify(m, null, 2) + '\n';
  });

  await edit(join(out, 'sw.js'), (s) => {
    let next = s.replace(
      "const CACHE = (self.APP_CACHE_PREFIX || 'instareport-admin-') + VERSION;",
      `const CACHE = 'instareport-${v.dir}-' + VERSION;`);
    // Never precache a file this variant does not ship.
    for (const dead of v.drop) {
      next = next.replace(new RegExp(`^\\s*'\\./${dead.replace(/[/.]/g, '\\$&')}',\\n`, 'm'), '');
    }
    return next;
  });

  return `${v.dir}: ${v.build.name} (ai=${v.build.ai}, db=${v.build.dbName})`;
}

const CHOOSER = `<!doctype html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>Insta Report</title>
<style>
  :root{color-scheme:light dark}
  body{margin:0;min-height:100vh;display:grid;place-items:center;padding:28px;
    background:#f2f2f7;color:#000;
    font:17px/1.4 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif}
  @media (prefers-color-scheme:dark){body{background:#000;color:#fff}}
  .wrap{width:100%;max-width:420px}
  h1{font-size:28px;font-weight:700;letter-spacing:-.02em;margin:0 0 4px}
  p.lead{margin:0 0 24px;color:#3c3c4399}
  @media (prefers-color-scheme:dark){p.lead,small{color:#ebebf599}}
  a.card{display:block;text-decoration:none;color:inherit;background:#fff;border-radius:16px;
    padding:18px 20px;margin-bottom:12px;box-shadow:0 1px 3px #0000001f}
  @media (prefers-color-scheme:dark){a.card{background:#1c1c1e}}
  a.card:active{opacity:.7}
  .t{font-size:19px;font-weight:600;letter-spacing:-.01em;margin-bottom:3px}
  small{display:block;color:#3c3c4399;font-size:14px}
  .credit{text-align:center;color:#3c3c434d;font-size:12px;margin-top:26px}
</style>
<div class="wrap">
  <h1>Insta Report</h1>
  <p class="lead">Building defect inspection reports. Pick the app for your role, then add it to your home screen.</p>
  <a class="card" href="./site/">
    <div class="t">Site &rarr;</div>
    <small>Capture defects, caption and annotate, send one file to the office. Works with no signal.</small>
  </a>
  <a class="card" href="./admin/">
    <div class="t">Office &rarr;</div>
    <small>Everything in Site, plus the AI assistant and the finished report.</small>
  </a>
  <div class="credit">Built by Ahmad Fudhail</div>
</div>
`;

await rm(DIST, { recursive: true, force: true });
await mkdir(DIST, { recursive: true });
const lines = [];
for (const v of VARIANTS) lines.push(await variant(v));
await writeFile(join(DIST, 'index.html'), CHOOSER);
await writeFile(join(DIST, '.nojekyll'), '');
console.log('built dist/\n  ' + lines.join('\n  '));
